apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sre-alert-tracker-data
  labels:
    app: sre-alert-tracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
