"""baseline: all tables

Revision ID: 958029e05409
Revises: 
Create Date: 2026-03-09 07:40:57.367834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958029e05409'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_filter_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False, comment='whitelist | blacklist'),
    sa.Column('filter_field', sa.String(length=50), nullable=False, comment='alertname | group | severity'),
    sa.Column('filter_value', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prometheus_url', sa.Text(), nullable=False),
    sa.Column('alertmanager_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='healthy | unhealthy | unknown | removed'),
    sa.Column('interval_hours', sa.Integer(), nullable=True),
    sa.Column('pull_info', sa.Boolean(), nullable=False),
    sa.Column('instance_label', sa.String(length=100), nullable=False),
    sa.Column('last_health_check', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('retention_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('retention_months', sa.Integer(), nullable=False),
    sa.Column('purge_cron', sa.String(length=100), nullable=False),
    sa.Column('last_purge_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'week_number', name='uq_year_week')
    )
    op.create_table('weekly_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('section_date', sa.Date(), nullable=False),
    sa.Column('operator_name', sa.String(length=255), nullable=True),
    sa.Column('daily_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['shift_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_windows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poller_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=False),
    sa.Column('lookback_hours', sa.Integer(), nullable=False),
    sa.Column('pull_info_severity', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(length=50), nullable=True, comment='success | error | running'),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id')
    )
    op.create_table('report_task_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('checked_by', sa.String(length=255), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['shift_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['weekly_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('daily_section_id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('alert_name', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('instance', sa.String(length=500), nullable=True),
    sa.Column('source_group', sa.String(length=255), nullable=True),
    sa.Column('runbook_url', sa.Text(), nullable=True),
    sa.Column('phenomenon', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_firing_at', sa.DateTime(), nullable=True),
    sa.Column('last_firing_at', sa.DateTime(), nullable=True),
    sa.Column('auto_resolved', sa.Boolean(), nullable=False),
    sa.Column('manually_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['daily_section_id'], ['daily_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_records_alert_name'), 'alert_records', ['alert_name'], unique=False)
    op.create_index(op.f('ix_alert_records_cluster_id'), 'alert_records', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_alert_records_daily_section_id'), 'alert_records', ['daily_section_id'], unique=False)
    op.create_index(op.f('ix_alert_records_fingerprint'), 'alert_records', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_alert_records_severity'), 'alert_records', ['severity'], unique=False)
    op.create_table('alert_record_labels',
    sa.Column('alert_record_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_record_id'], ['alert_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_record_id', 'label_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_record_labels')
    op.drop_index(op.f('ix_alert_records_severity'), table_name='alert_records')
    op.drop_index(op.f('ix_alert_records_fingerprint'), table_name='alert_records')
    op.drop_index(op.f('ix_alert_records_daily_section_id'), table_name='alert_records')
    op.drop_index(op.f('ix_alert_records_cluster_id'), table_name='alert_records')
    op.drop_index(op.f('ix_alert_records_alert_name'), table_name='alert_records')
    op.drop_table('alert_records')
    op.drop_table('report_task_assignments')
    op.drop_table('poller_configs')
    op.drop_table('maintenance_windows')
    op.drop_table('daily_sections')
    op.drop_table('weekly_tasks')
    op.drop_table('shift_reports')
    op.drop_table('retention_configs')
    op.drop_table('labels')
    op.drop_table('clusters')
    op.drop_table('alert_filter_rules')
    # ### end Alembic commands ###
